name: Windows CMake
on:
  workflow_call:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        type: string
        required: false
      run_test:
        description: "Whether to invoke CTest"
        required: false
        type: string
        default: 'false'
env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.extra_resolve_options }}

jobs:
  windows_cmake:
    timeout-minutes: 45
    strategy:
      fail-fast: false
    runs-on: [self-hosted, windows, cmake, builder]
    name: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CMake Cleanup
        run: cmake -E remove_directory ${{github.workspace}}/build
      - name: CMake Setup
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: CMake Configure
        env:
          GIT_SSH_COMMAND: "${{ 'ssh -i /home/buildbot/.ssh/id_ed25519 -o IdentitiesOnly=yes' }}"
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: cd build | cmake ${{github.workspace}} -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DSTEINWURF_RESOLVE_OPTIONS="--git_protocol=git@ $EXTRA_RESOLVE_OPTIONS"
      - name: CMake Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .
      - name: CTest
        if: ${{ inputs.run_test }} == 'true'
        working-directory: ${{github.workspace}}/build
        run: ctest
